//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: autopilotrpc/autopilot.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Dispatch
import Foundation
import SwiftGRPC
import SwiftProtobuf

internal protocol Autopilotrpc_AutopilotStatusCall: ClientCallUnary {}

fileprivate final class Autopilotrpc_AutopilotStatusCallBase: ClientCallUnaryBase<Autopilotrpc_StatusRequest, Autopilotrpc_StatusResponse>, Autopilotrpc_AutopilotStatusCall {
  override class var method: String { return "/autopilotrpc.Autopilot/Status" }
}

internal protocol Autopilotrpc_AutopilotModifyStatusCall: ClientCallUnary {}

fileprivate final class Autopilotrpc_AutopilotModifyStatusCallBase: ClientCallUnaryBase<Autopilotrpc_ModifyStatusRequest, Autopilotrpc_ModifyStatusResponse>, Autopilotrpc_AutopilotModifyStatusCall {
  override class var method: String { return "/autopilotrpc.Autopilot/ModifyStatus" }
}

internal protocol Autopilotrpc_AutopilotQueryScoresCall: ClientCallUnary {}

fileprivate final class Autopilotrpc_AutopilotQueryScoresCallBase: ClientCallUnaryBase<Autopilotrpc_QueryScoresRequest, Autopilotrpc_QueryScoresResponse>, Autopilotrpc_AutopilotQueryScoresCall {
  override class var method: String { return "/autopilotrpc.Autopilot/QueryScores" }
}

internal protocol Autopilotrpc_AutopilotSetScoresCall: ClientCallUnary {}

fileprivate final class Autopilotrpc_AutopilotSetScoresCallBase: ClientCallUnaryBase<Autopilotrpc_SetScoresRequest, Autopilotrpc_SetScoresResponse>, Autopilotrpc_AutopilotSetScoresCall {
  override class var method: String { return "/autopilotrpc.Autopilot/SetScores" }
}


/// Instantiate Autopilotrpc_AutopilotServiceClient, then call methods of this protocol to make API calls.
internal protocol Autopilotrpc_AutopilotService: ServiceClient {
  /// Asynchronous. Unary.
  @discardableResult
  func status(_ request: Autopilotrpc_StatusRequest, metadata customMetadata: Metadata, completion: @escaping (Autopilotrpc_StatusResponse?, CallResult) -> Void) throws -> Autopilotrpc_AutopilotStatusCall

  /// Asynchronous. Unary.
  @discardableResult
  func modifyStatus(_ request: Autopilotrpc_ModifyStatusRequest, metadata customMetadata: Metadata, completion: @escaping (Autopilotrpc_ModifyStatusResponse?, CallResult) -> Void) throws -> Autopilotrpc_AutopilotModifyStatusCall

  /// Asynchronous. Unary.
  @discardableResult
  func queryScores(_ request: Autopilotrpc_QueryScoresRequest, metadata customMetadata: Metadata, completion: @escaping (Autopilotrpc_QueryScoresResponse?, CallResult) -> Void) throws -> Autopilotrpc_AutopilotQueryScoresCall

  /// Asynchronous. Unary.
  @discardableResult
  func setScores(_ request: Autopilotrpc_SetScoresRequest, metadata customMetadata: Metadata, completion: @escaping (Autopilotrpc_SetScoresResponse?, CallResult) -> Void) throws -> Autopilotrpc_AutopilotSetScoresCall

}

internal extension Autopilotrpc_AutopilotService {
  /// Asynchronous. Unary.
  @discardableResult
  func status(_ request: Autopilotrpc_StatusRequest, completion: @escaping (Autopilotrpc_StatusResponse?, CallResult) -> Void) throws -> Autopilotrpc_AutopilotStatusCall {
    return try self.status(request, metadata: self.metadata, completion: completion)
  }

  /// Asynchronous. Unary.
  @discardableResult
  func modifyStatus(_ request: Autopilotrpc_ModifyStatusRequest, completion: @escaping (Autopilotrpc_ModifyStatusResponse?, CallResult) -> Void) throws -> Autopilotrpc_AutopilotModifyStatusCall {
    return try self.modifyStatus(request, metadata: self.metadata, completion: completion)
  }

  /// Asynchronous. Unary.
  @discardableResult
  func queryScores(_ request: Autopilotrpc_QueryScoresRequest, completion: @escaping (Autopilotrpc_QueryScoresResponse?, CallResult) -> Void) throws -> Autopilotrpc_AutopilotQueryScoresCall {
    return try self.queryScores(request, metadata: self.metadata, completion: completion)
  }

  /// Asynchronous. Unary.
  @discardableResult
  func setScores(_ request: Autopilotrpc_SetScoresRequest, completion: @escaping (Autopilotrpc_SetScoresResponse?, CallResult) -> Void) throws -> Autopilotrpc_AutopilotSetScoresCall {
    return try self.setScores(request, metadata: self.metadata, completion: completion)
  }

}

internal final class Autopilotrpc_AutopilotServiceClient: ServiceClientBase, Autopilotrpc_AutopilotService {
  /// Asynchronous. Unary.
  @discardableResult
  internal func status(_ request: Autopilotrpc_StatusRequest, metadata customMetadata: Metadata, completion: @escaping (Autopilotrpc_StatusResponse?, CallResult) -> Void) throws -> Autopilotrpc_AutopilotStatusCall {
    return try Autopilotrpc_AutopilotStatusCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Asynchronous. Unary.
  @discardableResult
  internal func modifyStatus(_ request: Autopilotrpc_ModifyStatusRequest, metadata customMetadata: Metadata, completion: @escaping (Autopilotrpc_ModifyStatusResponse?, CallResult) -> Void) throws -> Autopilotrpc_AutopilotModifyStatusCall {
    return try Autopilotrpc_AutopilotModifyStatusCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Asynchronous. Unary.
  @discardableResult
  internal func queryScores(_ request: Autopilotrpc_QueryScoresRequest, metadata customMetadata: Metadata, completion: @escaping (Autopilotrpc_QueryScoresResponse?, CallResult) -> Void) throws -> Autopilotrpc_AutopilotQueryScoresCall {
    return try Autopilotrpc_AutopilotQueryScoresCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Asynchronous. Unary.
  @discardableResult
  internal func setScores(_ request: Autopilotrpc_SetScoresRequest, metadata customMetadata: Metadata, completion: @escaping (Autopilotrpc_SetScoresResponse?, CallResult) -> Void) throws -> Autopilotrpc_AutopilotSetScoresCall {
    return try Autopilotrpc_AutopilotSetScoresCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

}

